apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: default-apps-monitor
  namespace: monitoring
  labels:
    release: monitoring-kube-prometheus
spec:
  # Kin namespaces me services ko dhundna hai
  namespaceSelector:
    matchNames:
      - default
  # Selector logic: All services matching labels in default namespace
  selector: {}
  endpoints:
  - port: http          # Service YAML me defined port ka name (e.g., 'http')
    interval: 15s       # Kitni der me scrape karna hai
    path: /metrics      # Metrics endpoint URL path
