name: Kubernetes CD Pipeline

on:
  workflow_run:
    workflows: ["Python CI Pipeline"]
    types:
      - completed

jobs:
  deploy:

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Backend Image
      - name: Build Backend Docker Image
        run: |
          docker build -t wahed1321/calculator-app:latest .

      - name: Push Backend Docker Image
        run: |
          docker push wahed1321/calculator-app:latest

      # Frontend Image
      - name: Build Frontend Docker Image
        run: |
          docker build -t wahed1321/calculator-frontend:latest ./frontend

      - name: Push Frontend Docker Image
        run: |
          docker push wahed1321/calculator-frontend:latest

      # Kubernetes Deployment
      - name: Apply Kubernetes Files
        run: |
          kubectl apply -f k8s/

      - name: Restart Backend Deployment
        run: |
          kubectl rollout restart deployment devops-app

      - name: Restart Frontend Deployment
        run: |
          kubectl rollout restart deployment frontend-app

      - name: Verify Deployments
        run: |
          kubectl get pods
          kubectl get svc
          kubectl get ingress
